
# Executive Summary 


The themes found in the discussion of the XOXO Community were the focus on: kindness and empathy, creativity, inclusivity, curiosity, emotional intelligence and community. 

When asked what people appreciated about the community, they remarked first and foremost on the people in the community and the the diversity of perspectives. Folks talked about using the Slack as a place to ask questions, gain information, to learn new things, to read the news, and to find links and creative things that people share. They described the shared values in the community such as upholding a sense of kindness, a political alignment and the idea that one should act without creating harm. Many people referred to the community as a place for kind and empathetic humans. Folks in the community valued creating a safe place with privacy. They also discussed the importance of the openness of the community. Folks spoke about appreciating the Portland channel and the ability to have another place besides social media. 

The concerns that people have about the community changing includes the worry of losing the community. A very robust theme was the fear that the community will splinter, fracture or fragment going forward. Folks worried about losing the network of people, and the contacts they had made as well as the resources in the community. They also talked about a fear of losing the XOXO spirit and the special something that made this place so important. Some talked about this slack as something they'd never find again, that it was different from anything else they'd experienced and that they saw it as a third space. 

Respondents said they could see some positive changes that a platform change could have for the community: it could signal an expansion, an evolution or a refresh of the community. Folks talked about being intentional about next steps and some of the opportunities that exist for decentralization. There was a sense that there could be changes in organization, moderation and making sure the community was sustainable. Others talked about the desire for new ideas, people, resources and events. Some also spoke of particular features and benefits that might come from changes to Discord in particular. 

Folks in the community described having concerns about platforms, as well as new leadership structures. Certain folks in the community talked about the importance of the community to them: folks who felt the slack had improved their mental health felt concerned that it would affect them negatively. People who lurk talked about the value they got from the community. 

When asked about the impact of the XOXO community on their lives, folks started with the quality of the community and how they had brought much of that way of thinking into other aspects of their lives. From finding friendships, meeting good people, to feeling at home, to being welcomed the XOXO community was a space that folks pointed to to show what community can be. Folks talked about it feeling like the "old internet" or "old twitter". Some folks talked about the diversity of people in the community, newcomers talked about really enjoying the community. 

Respondents spoke about the resources they gained in the community, the personal growth they experienced, the richness of the conversations they had. Folks talked about specific channels that had been impactful for them. During hard times, this community had also been a mainstay. Folks remarked on being in the Slack during Covid, and the ways that the Slack has helped them with their mental health and well being. Several people used the term "lifeline" when talking about the slack and many called it a safe space. 



Finally, the community had a thank you note to the Andys: 

Dear Andys, 

You're the best, we think the world of you. You made a community, one that was kind and that helped us remember the good internet. We saw how hard you worked. You changed lives and you should be proud of what you've done. We are so grateful and we the community will take it from here. Thank you. 

Love, the XOXO community 







