
# Executive Summary 

The first section of the report can be seen as a discussion of the values, impact and gratitude for the XOXO Community 

**[Chapter 3 - Community Values](https://bduckles.github.io/XOXOReport_BD/community-values.html)** 


### The Community 

The values of the XOXO Community as expressed in the survey were the focus on: kindness and empathy, creativity, inclusivity, curiosity, emotional intelligence and community. 


**[Chapter 4 - Appreciation For the Community](https://bduckles.github.io/XOXOReport_BD/appreciation-for-the-community.html)**

When asked what people appreciated about the community: 

* They remarked first and foremost on the **people** in the community and the the diversity of perspectives.
* Folks talked about using the Slack as a **resource** or a place to ask questions, gain information, to learn new things, to read the news, and to find links. 
* They described the **shared values** in the community such as upholding a sense of kindness, a political alignment and the idea that one should act without creating harm. 
* People referred to the community as a place for **kind and empathetic humans** and they valued creating a safe place with privacy and openness.  

**[Chapter 5 - Impact](https://bduckles.github.io/XOXOReport_BD/impact.html)**

When asked about the impact of the XOXO community on their lives

* folks discussed with the **quality of the community** and how they had brought much of that way of thinking into other aspects of their lives. 
* From  **meeting good people**, finding friendships, feeling at home, to being welcomed the XOXO community was a space that folks pointed to to show what community can be. 
* Folks talked about it feeling like the **"old internet"** or "old twitter". 
* Respondents spoke about the **resources** they gained in the community, the **personal growth** they experienced, the richness of the conversations they had. 
* Folks talked about specific channels that had been impactful for them. During hard times, specifically during Covid, the Slack has been a "lifeline" and supported folks in their mental health and well being. 


### What Happens Next 

The second part of the report can be seen as a discussion of what happens next: 

**[Chapter 6 - Concerns](https://bduckles.github.io/XOXOReport_BD/concerns.html)**

* Many folks feared the **loss of the community**, of the connections, of the resources and special XOXO spirit.  
* Responses reflected a fear that the community will **splinter, fracture or fragment** going forward. 
* They described **concerns** about new platforms, leadership and specific community needs. 

**[Chapter 7 - Platforms](https://bduckles.github.io/XOXOReport_BD/platforms.html)**

The top three platform contenders were Discord, Slack and Discourse. Functionality on both computers and mobile is important for this community. 

**[Chapter 8 - Platform Opportunities](https://bduckles.github.io/XOXOReport_BD/platform-opportunities.html)**

* Respondents said they could see some **positive changes** that a platform change could have for the community: it could signal an expansion, an evolution or a refresh of the community. 
* Folks talked about being **intentional** about next steps and some of the opportunities that exist for decentralization. 
* There was a sense that there could be changes in organization, moderation and making sure the **community was sustainable.** 
* Others talked about the desire for **new ideas, people, resources and events.** 
* Some also spoke of particular features and benefits that might come from changes by using **Discord** in particular. 

**[Chapter 9 - Platform Concerns](https://bduckles.github.io/XOXOReport_BD/platform-concerns.html)**

* Concerns included worrying that folks would disperse, we'd lose the network, the new platform would be unfamiliar and there'd be a loss of resources. 
* Some focused on challenges with **leadership structures**, moderation, costs and loss of the XOXO spirit. 
* Some discussed **functions in platforms** that could be possible with changes as well as specific comments about various platforms.   

**[Chapter 10 - Name](https://bduckles.github.io/XOXOReport_BD/name.html)**

The top contenders for names are: 

* And, And/&& (8)
* Enthusiasm Collective (8)
* Good Internet (7)
* Lowered Expectations/LoX/LOX/LowEx (5)
* YNYN (2)
* TKTK (2)
* Good Together (2)

### Thank you

The final chapter is a thank you to the Andys. 

**[Chapter 11 - Thank You](https://bduckles.github.io/XOXOReport_BD/thank-you-to-the-andys.html)**

Dear Andys, 

You're the best, we think the world of you. You made a community, one that was kind and that helped us remember the good internet. We saw how hard you worked. You changed lives and you should be proud of what you've done. We are so grateful and we the community will take it from here. Thank you. 

Love, the XOXO community 

**[Appendix - Survey Questions](https://bduckles.github.io/XOXOReport_BD/appendix---survey-questions.html)**




