
# Introduction

## What This Is 

This is a short, vibe check community survey of the [XOXO Fest Slack community](https://xoxofest.com/). In early October 2024, Andy McMillan and Andy Baio (sometimes collectively referred to as “the Andys”) who are the organizers of the festival and the Slack announced that because the festival ended, they would be closing down the XOXO Slack community that has been a mainstay of the community since the beginning of the festival. 

There was a lot of discussion in the Slack about what would come next. Some folks suggested we might want to do a survey to discuss next directions. In consultation with Pete Modica-Soloway, Josh Millard and Nora Ryan, I (Beth Duckles) put together this survey to start the conversation. 

We did a short one, mostly written survey with qualitative feedback to the community offering about a week to respond. There were 154 responses to the survey. Analysis was done by Beth Duckles and Rosa Quiñones.  

This report is meant to summarize the findings and to pull out key themes so as to start the conversation. 

## Lower Your Expectations

We have done a quick organization of the comments for each question into themes as a way to share the information that came from the survey. In each theme, we add a bunch of quotes in bullets that describe what we are seeing.

The qualitative coding/tagging (meaning grouping responses into themes) is rough, imperfect and it was done very quickly. We wanted the community have something fast more than we wanted to make it perfect. 

That means there might be a theme you see that we didn’t create, or something that fits with multiple themes. You might disagree with how we named the groupings, or you might think a quote in a theme is wrong altogether. 

All of this is great.  

If you think something is was placed in the wrong spot, or that we missed a theme or that it’s named wrong, you are probably right! You're invited to let us know, point out mistakes or to do another pass at it on your own or read the raw data in the dataset if you'd prefer that. Feedback is very welcome. 

The goal for this for paper was to create an easier way to start a community discussion, not a final "in stone" explanation of what everyone was saying. By reflecting what I saw/read in the data, I’m starting the process of summarizing to get our conversation going. 

Please, don’t worry about our feelings and go ahead and converse.


## The Overwhelm

This is LONG, so we understand that it might feel overwhelming. We made it long because we feel strongly that listening to the many voices of other people involves letting their words be at the center. So there are a lot (a lot) of quotes. You will certainly see the same quote in multiple places, often it's because the response had multiple points it was making.  

This may be overwhelming. I am sorry about that. We’ve done our best to summarize so you don’t have to read it all unless you want to. We encourage you to skip sections if you don't want to read something, or just go straight to the comments for the Andy's and commence weeping. Or not. You do you.

There are likely a lot of typos. If you feel strongly about this and want to contribute, you are warmly invited to copy edit what the researchers have written. 

However, in this kind of research, we don’t edit what people write in their response to the survey. This means that if there are typos in what people wrote, there are typos in how it is shown here. This is not meant to shame anyone, but rather to preserve what people say and how they say it. I don’t presume I know better how to say what someone else is saying than they do.

## Gift 

This research is a gift freely given to a community that has given me so so much. 

It is also something Beth has been able to do because she is between projects and has had the free time. Which means, I am looking for work. This is a small section of the kind of things I can do research-wise. Just think of how much more I could do if I was paid!  Come talk to me about doing cool community based research like this! 

If you want to talk to me about doing research projects for hire or want to drop a few bucks my way, I’m always up for it - find me on the slack at bduckles or beth@duckles.com. 


