
# Appreciation For the Community 

The question we’ll discuss in this section was “What do you appreciate about the XOXO Slack community?” Unsurprisingly, this mirrored much of what was discussed in the values section, but with deeper explanation. 

## The People 

By far, the overwhelming response to this question of what folks appreciate about the Slack is the other people in the Slack. 

*	I feel like I found my people here.
*	The caliber of people and the fact that it's about as safe of a space as I could imagine existing online. It might actually be the safest space online.
*	I appreciate the opportunity to connect with all the wonderful people in the community. This group of intelligent, connected and, attentive people have enriched my existence in many ways, including just talking about important or interesting things in a relatively safe environment.
*	so many incredible people, so willing to help each other
*	The people, the various emoji that say a thousand words, the different channels for different topics, the thread-first approach to communicating, the organisation of everything thanks to folks like the moderators, and even the very active members I recognise!
*	everyone is so awesome and kind
*	the people, the thoughtful responses
*	Local subject matter experts, friendly people, good discussion
*	People who are like me, openly sharing who they are, sharing advice, support, empathy and making every experience shared and a little less hard
* The lovely humans that make up the community and how they interact with each other
* It's an amazing place of creative people who are generous, kind, and a lot of fun. Also Andy Baio finds the best links. 
* The ability to assume truthfulness or good faith in the things that are shared, and the ability to be possibly wrong, possibly clumsy, possibly human
* The way everyone embodies the value above and leads through their actions
* the people, the content, the kindness, the attitudes, and the opportunity for closer conversations with lovely people
* The XOXO Slack community is helping and giving. People care. People are enthusiasic about things! People are really smart and interesting!
* People's willingness to be vulnerable and to hold space for others to be vulnerable
* All of those core values! And the sheer interestingness of the members of the community


### Diversity of Perspectives 

One of the attributes of the people that folks commented on was how many diverse perspectives they felt could be found in the slack. 

*	The people who are on it, come from a lot of different perspectives and backgrounds and that makes it more interesting
*	The variety of backgrounds and perspectives of participants
*	Diversity of perspectives, freely given knowledge, empathy and compassion for experiences, range of interests, learning and growing together
*	Such a breadth of experience and diverse skills in the members!
* That it's far more of a diverse community – along almost any axis, other than perhaps political leanings – than I would ever have access to in my day to day life.
* diversity, empathy, endless curiosity



## Resources

### Asking for Information 

Respondents discussed using the Slack to share knowledge, ask for help and to learn from one another. They described people being generous and helpful when they did so. 

*	I love having a place to keep up to date with links and stories shared in channels plus a place to connect and ask questions on a variety of topics.
*	When I have a question about damn near anything (resource, fact, local stuff, whatever) someone knows the answer and is likely to be similar enough in mindset to me that I can trust it. And, the goofy shit I like to share always seems to find an appreciative crowd
*	Breadth of channels. I can ask/answer Maker or home-improvement questions, keep up to date on tech/politics, and see folks being happy about stuff they made or found.
*	People’s openness to help, share knowledge, and generally be excepting
*	When I have a question about damn near anything (resource, fact, local stuff, whatever) someone knows the answer and is likely to be similar enough in mindset to me that I can trust it. And, the goofy shit I like to share always seems to find an appreciative crowd
*	Being able to ask all the dumb questions about anything and everything, and having really smart, capable people reply with their wisdom and resources
*	Ability to ask kind individuals both hard and easy questions across a variety of topics
*	People who are like me, openly sharing who they are, sharing advice, support, empathy and making every experience shared and a little less hard
*	Diversity of perspectives, freely given knowledge, empathy and compassion for experiences, range of interests, learning and growing together
*	Feedback and support
* Quality information 
* I appreciate the broad range of skills and expertise. I also love that we all are passionate about something and we're open to hearing about other's passions.
*	the ability to drop in and engage, the willingness of the community to provide support (responses, engagement, advice, etc.) and the depth and breadth of knowledge across all its members
*	I like that I have a place to hear about the things I'd hear about on social media (news, tech news, neat creative projects, dumb jokes) without the context collapse of social media, and in a moderated and kind environment. As a curated microcosm of the internet at large, I can dip my toe in and feel rewarded without getting hit with the anxiety and overwhelm - and the smaller scale means I've made some lasting friendships and connections because I'm able to show up more fully than I would if I was more afraid.
*	private identity channels; knowing that i can ask basic questions and people love info-dumping with no judgement
* It's a large group of smart, successful, creative, people who as a whole, is good-internet. I've made friends and professional connections here and my favorite by-product is the community's ability to help me gather information on almost anything, which also spoils me because I'm not confident in my abilities to find reliable information through traditional web searches.
* SO much. It's a place where I learn about and discuss current events and art with folks I like and admire. Also, frankly, it'a a place I can lurk! I expreience severe rejection sensitivity in online spaces, so the fact that I can pop a little emoji next to a post to show sympathy, curiosity, etc is really nice for me. I also experience the moderation as very present, compassionate, and firm, which REALLY makes a difference in the space.


### Learning 

Folks also discussed how important it was to learn from others in the slack and how much they had learned over time. People talked about how smart other folks in the Slack are and how intelligent the conversations were in the channels. They also described the space as being curated and having a variety of things they wouldn’t otherwise see/hear about. 

*	I learn SO much. There's so many smart voices.
*	The smart creative, mostly likeminded folks.
*	Local subject matter experts, friendly people, good discussion
*	Honestly, the “closed” nature of the community worked for me for professional reasons. But I also loved the diversity of topics and how it let me get to know different people from the general community.
*	Being able to ask all the dumb questions about anything and everything, and having really smart, capable people reply with their wisdom and resources
*	From the delightful shared experience of the Animal Crossing channel in early Covid, to the freewheeling discussion of politics, to the creative problem solving and solidarity of many other channels, questions, learning and growth are supported and so are the personal connections we’ve forged at the festival and in this digital space.
*	empathy, wisdom of the crowd, discovery
*	Diversity of perspectives, freely given knowledge, empathy and compassion for experiences, range of interests, learning and growing together
*	knowledge base
*	Curious, smart, politically progressive
* In depth and well meaning discussions on difficult topics - seeing people’s various opinions and considerations help me form my own
*	A large amount of very smart people all feeling like it's a safe place to express their thoughts
*	It's a large group of smart, successful, creative, people who as a whole, is good-internet. I've made friends and professional connections here and my favorite by-product is the community's ability to help me gather information on almost anything, which also spoils me because I'm not confident in my abilities to find reliable information through traditional web searches.



### News

Folks also described the slack as the place that they used to find the news, and that they relied on each other to have compelling and interesting conversations about topics that were on the front page of the newspapers.  

*	a way to get news, to get fresh and useful perspectives on news (politics and tech, mostly)
*	Great source for news & interesting projects from all around the internet, fantastic discussions with smart people who are experts on various topics
*	Resources in news/likeminded spirit
*	Discussions on the XOXO Slack are always my first choice for any online interaction, it's replaced all news sites
*	Excellent moderation, ability to check in for local Portland events plus national events (like politics and C19). My first go-to community for EVERYTHING, including classifieds.
*	Very up to date news, an active community, lots of channels dedicated to very specific topics
*	It’s a place where I can stay abreast on the difficult topics of the modern digital world and remain connected to other digital artists without the terrible emotional pain that comes along with using social media like Twitter
*	Surfaces good posts and news (replaced social media). People there make me feel seen. We don’t ramble, we share and support.
* I don’t like to consume news because of its ill effect on my mental health, and this Slack helps me stay engaged with issues I care about. I appreciate hearing the perspectives of this community.


### Cool Stuff People Share 

People described the benefit of being in a space where folks share cool stuff and they get to have curated content that they like. 

* Being able to stay in touch with friends made at XOXO. Seeing and hearing about all the cool stuff people make and share, whether from within the community or elsewhere. Recommendations on local and online businesses for specific needs.
*	Great source for news & interesting projects from all around the internet, fantastic discussions with smart people who are experts on various topics
*	Curated content, exclusive access, there are experts in everything
*	Fellow nerds and weirdos who read the internet so I don’t have to. Also I like that sharing is encouraged. I’m not someone with any real online presence so it’s nice having that space. Also, being able to have people productively disagree, though there have been a few instance of that being tested in the politics channel, the way it was handled by the Andy’s was I think very good.
*	empathy, wisdom of the crowd, discovery


## Shared Values 

Many folks talked about how they shared values with others in the community, including the upholding of the code of conduct, the sense of political alignment and a common belief in the idea that folks should be acting in ways that are not harmful. 

* it's a community with a shared *ethos* rather than shared subject matter, large enough to have lots of casual relationships/interactions but not the entire goddamn internet
*	It's the only social network that feels truly connected and wholesome. I use it to connect with a community of people that share my values, and know that the people sharing information care about the quality of their information, and will always act in the best interest of the community and each other. And if anybody acts in harmful ways, they will learn from their mistakes and act differently (or be removed from the community)
*	General political/social alignment, joyfulness, creativity, persistence of identity
*	A group with diverse backgrounds and experiences but shared values
*	Varied perspectives, but somehow lots of people with the same morals as you. Easy to make friends.
*	People who are like me, openly sharing who they are, sharing advice, support, empathy and making every experience shared and a little less hard
*	it's a collection of nice people who do interesting things, the whole community is invested in upholding the existing CoC/culture, the word "building" comes to mind (community/each other up/cool stuff/process/etc.)
*	Nearly everyone visible on Slack* appears committed to the core values of the Slack, providing a safe space for others, enforcing norms to that end, and politely accepting correction from others. There is a general understanding that not all behavior or speech can be welcome and still offer the safety needed to help people be and grow true to themselves. (*Behavior outside of this range may be happening and is not visible due to vigilant moderator efforts.)
* It's the only social network that feels truly connected and wholesome. I use it to connect with a community of people that share my values, and know that the people sharing information care about the quality of their information, and will always act in the best interest of the community and each other. And if anybody acts in harmful ways, they will learn from their mistakes and act differently (or be removed from the community)
* Learning from the breadth of knowledge and experience of my Slack pals in a place where we tacitly acknowledging shared beliefs that I can't assume are shared everywhere (caring for other people, respecting other people's experiences and privacy)


### Kindness 

Many, many people in the survey described the community as kind. Some examples: 

*	I have a group of kind, caring humans who give a shit.
*	Open minded people, kindness and empathy centered, a bastion of covid-awareness.
*	I appreciate how people are supportive and share their thoughts
*	Positivity, curiosity.
*	People who are like me, openly sharing who they are, sharing advice, support, empathy and making every experience shared and a little less hard
*	The kindness and enthusiasm
*	Same thing! All the creative, kind people. The commitment to inclusivity and authenticity
*	everyone is so awesome and kind
* The kindness, the knowledge, the generosity of spirit of everyone involved.
* everyone is so nice and we assume best intentions! also each account is one real person who has presumably interacted with the other people here IRL at least once, as part of a larger network (which lends some accountability/responsibility)
* People are nice to each other. There are regular characters. The usual Slack conveniences that make it possible for people to not repeat themselves and to let me ignore US politics if I want to.
* the small acts of kindness or indications of support people offer each other; emoji indications or threaded replies have genuinely lifted my spirits







### Safety
One of those shared values seemed to be safety. People consistently referred to the slack as a safe space, or a place were they felt they could be themselves. They also commented that this made the space trustworthy and easy to be in. 

*	people assume good intent and read with compassion and reply with civility; it's a safe space for people with marginalized identities, people are funny and kind and creative and there's very little 'rock star' attitude (even from people who are literally rock stars)
*	The safety and established trust.
*	The caliber of people and the fact that it's about as safe of a space as I could imagine existing online. It might actually be the safest space online.
*	It seems like both a safe place for optimism and constructive criticism.
*	A safe place for me to land for professional and personal needs
*	I love having a place full of people I respect and admire, where I nonetheless feel safe being honest and vulnerable.
*	It is consistently the kindest space I'm a part of. It's also the largest space I'm a part of that feels private and provides safety in its privacy.
* Such a thoughtful space! I do not know how much moderation it requires, but from the outside it is a smoothly functioning space full of independent-minded folks, which is no small thing! I feel safe and cared about, even by relative strangers.

People also described this as a place with people they could trust 

*	My views align with those around me, and I enjoy chatting with people who share common ground. Since we all respect the code of conduct, there's less negative behavior, making interactions smoother. I value learning from the random, niche interests everyone brings, as someone always has expertise in something I’m curious about. These diverse perspectives help me expand my understanding and knowledge.
*	The broad spectrum of experiences and knowledge so that I can find out about a lot of different topics, from people who I feel like I can trust because they've been vetted.



### Privacy 

Some folks linked safety with the privacy of the space. 

*	It is consistently the kindest space I'm a part of. It's also the largest space I'm a part of that feels private and provides safety in its privacy.
*	Honestly, the “closed” nature of the community worked for me for professional reasons. But I also loved the diversity of topics and how it let me get to know different people from the general community.
*	The wide world will never see it so I can really be myself


### Community 

People discussed community as something that they felt a part of, that was important to them and that they shared with others.  

*	It’s a very welcoming community, there’s a shared sense of how hard it is to make things and an appreciation of what people do
* It gives me a hometown, which I haven't had in ages and ages
* I like how people don’t jump to knives at the first opportunity, and appreciated that an Andy would step in and lay down the kindness law, gently then firmly, if needed, while not putting down one side or the other.  I also like how people are able to browse and find others who have similar interests by looking at the channel list.  I like that there are private spaces, as well.  I also appreciate the 'benevolent dictators' both the structure but also that our dictators are kind, patient, and passionate.
*	The ease of re-engaging after varying levels of activity, but also a core group of active members. This is the only only community I’ve belonged to where I feel most comfortable expressing opinions and not competing for popularity. In other social networks, I’m often forced to create separate identities for friends/family, private, and professional audiences.
*	the ability to drop in and engage, the willingness of the community to provide support (responses, engagement, advice, etc.) and the depth and breadth of knowledge across all its members
*	it's a collection of nice people who do interesting things, the whole community is invested in upholding the existing CoC/culture, the word "building" comes to mind (community/each other up/cool stuff/process/etc.)
*	it sits perfectly at the intersection of art, technology, nerdery, and social good. there are plenty of communities that bridge two of those things but I haven't found another that covers off on all of them like XOXO does.
*	The ability to communicate with others across multiple points of interest and the opportunities for mutual aid through ideas, concepts, and real world help.
* Connection. This community has gotten me through some really hard times and while I may not know many of the folks here in person, I consider many of them friends. 
* #portland and #classifieds for local connection, #good-internet / #politics-and-news / #tech-culture to keep up with relevant news and events
* Ability to vent and then find distractions and cool things and inspiration
* So many things. It's a place to go with wild ideas, or burning questions, or amusing anecdotes. It is a place to be supported and to give support.


### Openness

People also described the community as open: 

*	People’s openness to help, share knowledge, and generally be excepting
*	Open minded people, kindness and empathy centered, a bastion of covid-awareness.
*	Openness, creativity, sharing and support
*	that it's open, helpful, welcoming, entertaining


## Portland 

Folks in Portland in particular talked about how useful the slack was to find things in their community. 

*	I'm a lurker, more than a poster. The #portland slack has been incredibly valuable as a local. I've attended events, visited restaurants, learned about civic activities, and donated to causes I learned about via Slack.
*	For Portland especially, xoxo is a wonderful resource of news, vendors, events.
*	Its relative privacy and safety, most of the cool new things I've learned about in Portland and on the Internet were via this Slack.
*	It's been a really good resource for things going on in Portland Oregon! Otherwise it's just nice to see what people are up to or reading.
* feels like the small room of good internet circa 2010-2015 and/or like Twitter before it got bad. Secondly, as a new native to Portland I really appreciate participating in a community of like-minded local creators


## Alternative to Media 

Some folks talked about the community as a place where they could have a discussion that wasn’t as broken as some of the media we have now. 

*	It’s a group that cares about and wants the best from the Internet, but without the blind techno-Utopianism of mainstream tech culture.
*	I like that I have a place to hear about the things I'd hear about on social media (news, tech news, neat creative projects, dumb jokes) without the context collapse of social media, and in a moderated and kind environment. As a curated microcosm of the internet at large, I can dip my toe in and feel rewarded without getting hit with the anxiety and overwhelm - and the smaller scale means I've made some lasting friendships and connections because I'm able to show up more fully than I would if I was more afraid.
*	It’s a place where I can stay abreast on the difficult topics of the modern digital world and remain connected to other digital artists without the terrible emotional pain that comes along with using social media like Twitter
*	A digital shelter from a capitalistic web
* It helps keep me centered in a greedy, competitive world.
* nice place for nerds to nerd out



