
# Concerns 

We asked folks “What concerns (if any) do you have as the XOXO Slack winds down?” 

Folks expressed their sadness about the loss of the community, loss of connection, resources and that special XOXO spirit. There were concerns about new platforms, new leadership, and several different groups in the community expressed their concerns. 

## Loss

### Losing the Community

People were very concerned about losing the community that was built. 

*	Significant loss of community and support
*	I am concerned that I will lose track of folks and the important, silly and entertaining chats we have
*	Losing touch with the community
*	We will lose people.
*	It will be hard to find “my people” again in other places
*	The lack of community that has a baseline of trust good enough to bring its users forwards. I won’t have people to bounce ideas off of who I know share my values, I won’t be able to look for jobs with people that share my moral code. It’s tough.
*	The community won’t continue, I’ll no longer be in a vibrant internet community
* Losing connection and  community — I’m kind of terrified of what my world will look like without this space (but I definitely understand and respect the decision). 
* massive dropoff in participation/access, potentially less user-friendly new platform, increase in anonymity, potential decrease in community trust/network 
* I stumbled upon the after-slack channel kinda randomly and had no idea it existed or that the slack would be winding down, and I’m kinda surprised there hasn’t been a post in #announcements about it to get more people aware and involved. 
* That I won't be able to engage with a community I've come to appreciate and speak/discuss things in a friendly and safe space.


### Fragmentation

Folks mentioned worrying about the splintering, fracturing or fragmenting of the community. 

*	Fragmentation of the community. Or a replacement that doesn't allow for the same breadth of topics and discussions. Discord sucks at threading, and threaded topics keep a lot of the xoxo slack legible and approachable. I just don't want to lose these people, or the quality of the discourse we have.
*	I worry that this community will fracture in a way that will eventually fizzle out. We all care where this goes, but that doesn't necessarily make it easy.
*	The community splintering a bit (inevitable) as some point just won't migrate to certain platforms probably
*	Splintering of the groups into isolated subgroups that are harder to find.
* I really think that we'll never be as central as we are now; we're going to scatter and lose track of each other
* The community fragmenting into many different new spaces and it being difficult to know where everyone went
* I think the community will scatter, so it's not really a concern, but it's something I'm sad about.
* I'm worried the community will fragment and it won't be as diverse and full of a wide variety of experiences and viewpoints.
* Fragmenting the community, not replicating the x-channel experience elsewhere, fear of choosing an under-supported chat/forum solution and running into maintainence difficulties and seeing the community die out
* Fears: 1. the community scatters to the wind without a clear locus 2. community gets fragmented 3. no other such community exists /cannot be replaced 4. do not want to lose this both local & extended community


Similar to the worries about fragmentation were folks worried about the lack of coherence in a new setting. 

* I feel concerned that a group won't cohere in a new place, and that values and conduct will be harder to manage without the same leadership.
*	Maintaining connections with people from this group without having to join a lot of small things in different places
*	I don't want to lose the community we created


### Loss of Contacts/Connections/Networks 

People also worried about the loss of the people they know, and the contacts and network that the community is made of:

*	that we'll all scatter to the winds
*	losing touch with locals and those I rarely see
*	I really rely on hearing from my friends in my little pane of glass every day, I don't know what I will do w/o them
*	Losing regular contact with the community who shared those core values
*	I really appreciate this tiny corner of the internet and all the voices; will be sad if it goes away completely!
* disintegrating connections/strong as well as distant relationships, lost art and humour and logs of supportiveness, loss of casual but trusted and confident advice and recommendations 
*	Just that I’ll miss every one.
* I'll miss people (en masse), though I don't know anyone well enough to actively keep in touch
*	more work to connect with people outside the Slack
*	losing touch with people I've met, losing the breadth/diversity of content and opinions. I love how many amazing things I have discovered beit art or technology projects or information about local activities that I wouldn't have known about if not for this community.
*	Losing that incredible social network both in terms of resources but also in just enriching my daily life
*	Speaking entirely selfishly, I'm worried that I will lose contact with a network of artistically successful, like-minded, and supportive people. I'm not a member of other communities so capable of helping me do better work or promote that work, and otherwise connecting me with opportunities that interest me (employment or otherwise). XOXO Slack is both private *and* populated with people I admire in various fields, as well as friends I don't otherwise have contact with. I have IRL friends and other online communities, but no group as diverse or as interesting as XOXO. I can't imagine building such a network from scratch today, especially with the degradation of online social networking tools.
*	Losing this community of amazing people.
*	i'll miss being able to connect with this group of people, and seeing the fascinating things they share and make
*	We’ll loose a lot of people and breadth of experience
*	Not having a place to vent, losing contact with people I care about, not having a place to process emotions and seek advice and talk about things like ptsd, anxiety, depression, impostor syndrome and also feeling alone when I don't see others going through the same things
* Losing touch with some of my favorite people on in the internet (only a few of whom I've met IRL)
* Missing out on turning those weak connections with peers in channels into far greater friendships.
* I'm concerned about losing touch with people, and about losing an active stream of content/conversation
* Losing track of everyone and all of the great resources and conversations. Losing the job board.


### Loss of Resources 

Folks talked about the resource of the community and their fears about losing those resources. 

*	I'm worried I might lose some of those resources and community at a time when online spaces already seem to be shrinking.
*	Losing a source of important things happening in the world, losing a source of positive information.
*	I fear that I will lose access to an important source of information and I’ll end up having to stay up to date in stressful spaces
*	losing the incredible resources of this community
*	Keeping all that varied input together
*	Losing all of the incredible resources/recommendations that I’ve saved there as well as all the people I’ve connected with who I’m maybe not connected with on other areas of the internet
*	The splintering of the community and loss of archive. The strength of the community comes from the interactions between folks. I explore the slack daily and learn so much and interact as much as my stamina can handle. Sometimes often, sometimes not. but! The variety of opinions and conversations is so important and ensuring there's minimal friction for folks to engage is important. I also search the archives for help and having a persistent record is useful to me.
* disintegrating connections/strong as well as distant relationships, lost art and humour and logs of supportiveness, loss of casual but trusted and confident advice and recommendations 
* Loss of creative ballast and diminished trust in humanity.
* Not being able to connect to people whose opinions, feedback, and camaraderie I’ve grow to trust and rely on


### Loss of Special XOXO Spirit 
There was also a sense of loss of the intangible sense of the spirit of this community 

*	Initially, the new space doesn't _sufficiently_ capture the spirit. Long-term, that it degrades.
*	While it’s probably inevitable that a platform shift will cause some people to drift away/not come with, I am hoping there is something that reflects the same core values of the Slack community in a sustainable (financially, emotional labor-wise) way
*	This Slack also had a subtly reinforced etiquette amongst active users, like threading topics, redirecting to niche channels, or contextualizing shared links. I fear a new platform will drive a wedge between active core users, seasonal festival users, and new non-XOXO members. Each channel also differs in etiquette and moderation, which can be lost in translation when migrated.
*	Losing people, losing the intangible thing that exists on the XOXO Slack
*	Keeping the same community and thoughtfulness together on whatever new platform
*	that the magic will dim; this is reliably my favorite place online
*	Losing people, losing the intangible thing that exists on the XOXO Slack
* Scared we won't catch this vibe again, and will end up with a rump-xoxo slack that is somehow sad
* Losing instances of kismet or good luck which occur when a very large group of talented people are all drawn to the same place - there's a kind of magic to being surrounded by people who are also devoted to both kindness and trying their best at what they do. There are not many places in the world where I could say as an artist, “Randomly, I’m obsessed with these repeat-pattern window films” and someone says “Oh, my wife is half of that design team!” and now we’re in touch and might get to make cool stuff 


#### I'll Never Find Something Like This Again

Among the ways that folks talked about their fear of losing the special spirit was with phrases around how hard it would be to find something like this again. 

*	I will never find such valuable community
*	I'll miss it and it won't be replaced with something else.
* I really don’t know anywhere else like this :(
* I don't know where I'm going to find another similar community, or to find these people elsewhere!
* I’m just worried I won’t be able to find the next spot!


#### This Slack is Different 

Several folks also remarked that this place is different than other types of social media and so it cannot be easily replaced with another platform or group of people. 

*	I'm going to lose all the friends I haven't made yet! And I don't want to be on public social media.
*	The cross discipline nature of the whole group adds so many perspectives and variety to conversations. More topic-focused successors might lose that.
*	losing insights on tech that aren't awful and are instead optimistic, losing local (Portland) knowledge base
*	Loosing instant access to a wonderful community of people that has filled the social media hole in my life after deleting everything but LinkedIn.
* I am just so sick of everybody-has-a-megaphone performative-outrage social meida sites.

#### Slack as a "Third Space"" 

Other folks talked about the slack as a sort of “third place” or a spot that one returns to. Some folks talked about it as a water cooler or a place to hang out. 

*	I really rely on hearing from my friends in my little pane of glass every day, I don't know what I will do w/o them 
*	Lose touch with people, lose my "third place" where I have felt the most comfortable online.
*	I work from home and it's my main watercooler! Will miss that and hope the replacement functions similarly.
*	It’s my favorite place on the internet

## Concerns About New Platforms 

Some folks shared their concerns about new platforms

*	Future loss or disassociation from the historical community record, challenges with invitation/openness to new users on a new platform
*	i'm not going to use discord and that seems like it will be where yall go
*	Keeping the same community and thoughtfulness together on whatever new platform
*	It was my favourite Slack for sure, but I don't think it necessarily has anything to do with the technology. It could have been a web board or a Reddit or whatever made the moderation and the delicate balance of inclusion and exclusion work. I would be excited to join another or multiple communities that spawn from here based on their mandates. Being able to talk about culture and technology and art are important to me and the lack of geographical boundaries benefitted me living outside of a major US city.
*	Which platform we end up on. Will a free tier slack work for us? Will discord's gamer stink scare people away? Will a third option for our needs? It's hard to know!
*	Having to learn to navigate a new non-slack on line community. I like Discord.
*	That the community has an easy transition to a new space, without unnecessary technical barriers, and that whatever comes next (at least initially) remains as a closed community.
* I really dislike Discord and am worried we'll either get fractured into so. many spaces we'll lose the magic that exists on Slack or that we'll move to something I'm not comfortable with and don't want to be on. * I worry we will end up on some corporate platform and be in the exact same situation in a few years
* I want us to find a new home that can stay as dynamic and vibrant. That can be appreciated in both real time and periodically.


## Concerns about Leadership 

Some voiced concerns about whomever assumes the leadership of what comes next. 

*	This grew organically and thoughtfully as an outgrowth of the conference. I worry about platform, lack of Andy’s-ness.
*	I'm a little worried about new leaders making decisions that drive folks away, but I'm much more worried about nobody taking the reins and everyone slowly fragmenting and dispersing.
*	Super tough for whoever decides to take on volunteer responsibility
*	We've been able to operate a digital space under implicit values and norms established by the IRL event. Without the Andys as our benevolent dictators (even if in actuality much/most Slack moderation wasn't done by them), and potentially without the context of IRL XOXO if we eventually let in outsiders, recreating the same psychological safety will require more work. I'm also concerned about community attrition; an "unofficial" thing without an annual event may be more difficult to maintain healthy numbers (which ties into potentially bringing in new members)

Some discussed concerns around governing with a new leadership 

*	how do we govern the new space? how to avoid a single mercurial owner-member shutting it down abruptly? can we pay folks to moderate/manage the community? or is it something like a nonprofit board? this community is worth paying for.
* Governance, if building trust in the new decision makers
*	What comes next? How should it be similar and different? Will I be allowed into the next thing? If something new spins up, how could I contribute to it's sustainability and success?
*	Retention and activity with inevitably drop, members may place unrealistic or high demands to match the current level of moderation on the new team
*	I think charismatic leadership/tone setting and moderation should be separate functions, as they require two different strengths; one requires openness and vision, while the second requires more rigidity and control.
* how do we make decisions as a group?
* The xoxo community belongs to the community. How can these decisions be make without the community 




## Community Needs

Different groups in the community talked about their specific needs.  

### Mental Health and Well Being 

Some folks in the community talked about their mental health being greatly enhanced by the community and their fears about the loss of this community going forward. They said that the Slack combatted their loneliness, their doomscrolling and that it contributed to their well being. They were concerned that their lives would be worse without it. 

*	To lose the great connections, inspiration, advice and live a lonelier life
*	loss of community, disconnection, isolation
*	Losing a community that is a vital pillar of my mental heath with no idea how to replace it if we don’t figure out a way to keep it going.
*	Not having a place to vent, losing contact with people I care about, not having a place to process emotions and seek advice and talk about things like ptsd, anxiety, depression, impostor syndrome and also feeling alone when I don't see others going through the same things
*	I doomscroll again
*	I’m very concerned about losing this space as the internet becomes more hostile.
*	I feel very socially isolated right now and this going away is going to make that worse
*	The XOXO Slack has been a valuable resource for me, both as a news source (as someone who doesn't spend any time on public social media) and as a community. It has been especially valuable during the pandemic. I would really miss having that connection to a group of similarly pandemic-cautious people to remind me that it's the rest of the world that's making wild choices, not us.


### People who Lurk 

Folks specifically brought up the topic of folks who "lurk" in the slack and don't post much. 

* I imagine there are a lot of lurkers who still get a lot of value. Personally I actually add to a conversation like once a month maybe? And I’m worried that any sort of “oops it all fragmented into a million communities” will maybe impact those folks the most. Though maybe part of community is participating, so idk.
* the xoxo community (and slack) is made up of all of the people, lurkers as well as active posters.  I worry that the new community will only have currently active people who will try to attain a kind of nostalgia instead of allowing it to move forward in a way that preserves our shared ideas of community

### Newcomers

Some respondents highlighted the difference in responses for those who are newer to the community: 

*	being new in 2024 means less of a 'loss' for me personally, in terms of a history with the slack, but that belies a concern that longer or more tightly-knit cohorts that have existed throughout will splinter off and those newer folks may not have that or as easy an ability to catalyze a transition as those older folks with more historical relationships in the community, so an understanding of that and some way of making sure there isn't so much slipping through the cracks if there doesn't have to be
*	The thing is that I want this to be an opportunity for growth, including opening up invitations eventually. I know not everyone will make the jump, and even less will be frequent users, but I really hope this is also an opportunity to bring in new voices. I was a volunteer this year, and some thing that Andy said was to be mindful of the fact that for many people this was their first XOXO, so don’t make it all about sipping on the sweet nectar of your memories. I want the next chapter to be like that, but more. sorry for the long answer


## Additional Comments 

### Positive Words

Some folks shared words of affirmation or enthusiasm for what comes next instead of concerns.

*	I am confident that the community wants to continue.
*	This is a curated group and allowing new people in will change that in fundamental ways. I think it's okay if the community "winds down" (fewer users) because there's still a core happening, and people can come back in as their own needs change.
* I'd be sad to see the community drift apart; so glad there's an effort to create a new one!
*	In truth, it will evolve, but never be the same. It's like an unconference, the experience just happens there and just for the people there. It will live on, just in a different way
*	I suspect that I will not be as comfortable, sharing more personal things in any other forum. And that’s OK. This is giving me an opportunity to reach out to the people they would like to stay in touch with.
*	While it’s probably inevitable that a platform shift will cause some people to drift away/not come with, I am hoping there is something that reflects the same core values of the Slack community in a sustainable (financially, emotional labor-wise) way


### I'll Go Wherever 

Some said they would go to whatever comes next: 

*	Would like to follow the diaspora to other venues
*	I don't really care where it goes, as long as it survives.

### Missing the Emojis 

*	I’ll miss the custom emojis; they were a second language to this community.
*	i will feel like i have lost a ton of my working vocabulary if we lose all our reactji! and I will very much miss people who for whatever reason can't transition to whatever comes next



### More Thoughts 

*	No concerns really, it’s just sad
* Privacy and safety. What prevents people from screenshotting and sharing once channels go inactive? What rules will there be for this new era of interaction with the archives?
* Keeping various sub-communities (channels) and safety of the space 
