
# Name 

We asked "What do you think the new community(ies) should be named?" 

## Top Contenders 

I've listed out any name that was voted on with more than two votes (with variations) and the approximate number of votes. 

* And, And/&& (8)
* Enthusiasm Collective (8)
* Good Internet (7)
* Lowered Expectations/LoX/LOX/LowEx (5)
* YNYN (2)
* TKTK (2) 
* Good Together (2) 


### Other thoughts
* JabbawockeeBook
* YOYO
* The Imposters 
* Someplace
* Elsewhere
* Good Together 
* NeD
* YOYO
* TskTsk
* Dandelion
* With Love
* and/or
* ZIZI
* Mutiny
* Delicious Burger
* Restart to update
* Indie Internet Appreciation Society
* Amalgamated Enthusiasm
* Death Form for Cutie
* Life Raft for Cutie
* The Grove (or something nature/wilderness based)
* Kinfolx
* Murmur
* A Very Low Number of Dingalings
* Amalgamated Enthusiasm
* Patchwork 

### Inside Jokes 

Folks had thoughts about it being an inside joke. While most didn't want the inside joke to be too involved, there were some that thought it would be good for it to refer back to jokes and conversations in the community. 

* Something that’s not an in-joke from the in-person stuff or would be off putting to future potential new people
* YOYO. Don’t really care. But I think a connection to the festival or shared values is important. Lowered Expectations and The Imposters are also good choices: festival-specific inside jokes, but also close to the values and personalities of attendees. Yo-yo works as a name since most of us are bouncing up and down between pride and insecurity.
* Personally I would avoid deep in-jokes from particular years of the festival
* No preference. But maybe avoid anything that's too deep of an inside joke.
* I just don’t want it to be an inside joke. Like the death cab or 21st September thing, neither of those resonate with me and I think they’re pretty played out. Whatever it’s called, it should stand on its own.

### Comments 

* please nothing with & in it, otherwise very open
* I liked Dandelion from that one thread of names.I think && is fun, but also maybe annoying to refer to? Then again we've been saying X-O-X-O for a decade haha
* Something that speaks to the core values of the group while being as inclusive as possible (eg no inside jokes).
* Maybe a name that can evolve as the community changes.
* YOYO. Don’t really care. But I think a connection to the festival or shared values is important. Lowered Expectations and The Imposters are also good choices: festival-specific inside jokes, but also close to the values and personalities of attendees. Yo-yo works as a name since most of us are bouncing up and down between pride and insecurity.
* Pool some money together and buy Twitter brand


### Don't Care 

Many folks did not care, didn't know or expressed a desire to use whatever the community decided. 

* I’m open to anything
* Not that important to me, tbh.
* I have no strong opinion
* I’ll use it no matter what it’s called.
* Ooh I have been trying to think of a good name and cannot. I'll leave it to the more creative folks of our group lol
* No good ideas here 😅
* I don’t have a strong preference so far.  There have been a lot of clever suggestions and, I am down for whatever resonates with the most people.  A rose by any other name …
* Oh gosh honestly I don’t know!
* I don't have a strong opinion here. I don't feel a strong need to reference the old community or conference or Andys in the name.
* No preference
* I'm ambivalent, or without much concern or preference for naming.
* I have no idea, I accidentally named a mascot Darryl Scroggins because I hate naming things so I try to suggest bad names so people stop asking me
* I really don't have an opinion here.
* No idea! Naming stuff is hard
* defer to the thread on slack


### Variations on XOXO: 

These are likely to not be a good fit after the Andys requested we not use XOXO in the next name. 

* The XOXO Netflix Film Community
* XOXO Alum (tie)
* exoh
* exes
* oxox? I am bad at naming things.
* XOXO alumni
* OXOX? Oxenfree?
* Xoxo community!
* OXOX
* something XOXO
* XOXII
* Xoxo Alumni
* ExOXO
* OX
* XO2O



