
# Impact 

We asked the community: What would you like to share publicly about how the XOXO Slack has impacted your life? 



## Quality of the Community 

Responses talked a lot about the quality of the community and how the community felt like an example to them of what good community and good internet could look like. 

* XOXO Slack is one of the only online spaces where I feel like I'm connecting with an actual community of people willing to give me consideration as a person, where I can try new things, make mistakes, and trust that I'll receive both well-meaning feedback and forgiveness. We can chat and share casually about a wide range of topics without so much concern about a hypothetical future entity using what we say against us disingenuously. I can strive to be a good person, and not just self-censor to where I look like one."
* This community has changed my life. I've made lasting friendships and received career altering advice and assistance from the generosity and intelligence of the people assembled.
* XOXO slack is hugely important to me as a source of community. Also (and far less importantly) I get a lot of cool links from the slack that I use to make it seem like I'm cooler in other communities
* Xoxo slack provided community during the darkest time of the pandemic (and beyond) . I often feel isolated from creative communities which can be cliquish. Xoxo slack is the best type of inclusive community: bringing people together to learn and grow as responsible creative beings on this planet.
* This community has been the closest to feeling like “my people” of anything I have ever experienced.  People here have been consistently welcoming and friendly.  I learn about things I otherwise would have missed on an almost-daily basis.  I feel honored to have this kind of access to so many amazing folks.  XOXO and this community have encouraged me to be less shy about sharing things I do and make.
* I have always struggled to find a home on the internet. It's hard to join an existing community, and it's also hard to create one yourself. The XOXO slack always felt like such a welcoming place to just be. I really appreciate what it has been, and will miss it dearly – but I look forward to whatever is next.
* The XOXO slack is the first place on the internet where I felt at home.
* I have always struggled to find a home on the internet. It's hard to join an existing community, and it's also hard to create one yourself. The XOXO slack always felt like such a welcoming place to just be. I really appreciate what it has been, and will miss it dearly – but I look forward to whatever is next.


### An Example of Community 

Folks referred to the community as something they point to as a good example of what community can be. 

* Hard to define because it's been an accumulation of small things that have contributed to my whole identity. I'm not just my job, or my work, or my movements — I'm also part of this community, this culture. The examples you all set have informed how I try to act and be, both online and offline. And of course the Andys' example of collaboration and leadership will always be a part of everything I do with others.
It's taught me how to be more inclusive
* this Slack has shaped my thinking about communities and how they work, as well as being an incredible support and resource during a very intense period of my life and in the world. it's one of the only places where I still seek out news and politics, partially because of the ethos of the space. oh! and it's where I found one of my closest co-workers for a couple of years, who is still a very good friend. during a period when so much of the internet became completely unbearable, the xoxo slack remained a constant reminder that good people are doing cool stuff, and that we can all take care of each other.
* Renewed my faith in online community
* It has given me a higher standard of what forums/communities can be. It's helped me keep on writing in my blog even if I don't get a lot of traffic because at least I'm creating something.
* I've said it before but the XOXO Slack has been one of the best internet communities I've experienced, and I've learned so much from the community there. I wish everyone were able to find a community like this one to see what's possible, particularly given the way that social media has become so fractured and hostile.
* It has been my connection to my city and the people within it for so long, I barely know how to deal with it changing or going away. Every day, it's one of the first things I see.
* The XOXO Slack has been a lifeline for me since 2018. It is a safe and caring place I can go for inspiration and information and assistance and a laugh and new music and job postings. I enjoy supporting others in the community. Being in this community gives me confidence in what I'm doing professionally. I don't feel alone. I know that people care and that there are other people like me. I am so inspired and moved by this community and the people I've met here.


### Community Feels Like Old Internet  

Folks often brought up the idea that this felt like the "old Internet" or "Old Twitter" 

* It feels like one of the last bastions of "good internet" that has roots going back to places like The Well, Suck, etc., and that still lives on, but is increasingly hard to find unless you know where to look.
* It's the only social network I use that feels truly social for social's sake. I trust the community, and love being able to talk with people who share my values, love of the internet, and curiosity about the world and how to make it better.
* as someone who's been terminally online since I was in my teens, I've felt disconnected from my older communities as I've aged. This community feels like my last best connection. It's been the first place I turn in so many moments over the last 5 years
* XOXO Slack is one of my last remaining connections with the spirit of the Old Web and the early weblog community. Optimism, creativity, connection, exploration of the creative and social spaces formed by the tools we use to create and communicate, and sensitive and sober consideration of the social responsibilities of those technologies.
* Since then I've been mourning the loss of my community. Many left with me, but we all scattered to different places. The people in this slack are different (with some overlap) but it really is a community and it feels a lot like Twitter back in the fun days. It has helped me process the loss of Twitter and come to terms with the fact that all communities evolve, change, and dissolve. A community is not defined by the people who are in it, but by the relationships and care that flow between the people. (As in most graphs, edges convey more information than nodes.) 
* It was a great way to keep up-to-date with the fest itself but also the communities and topics that interested me. Like "old" twitter, I could find a place to co-watch the Apple keynote, for example.
* Social media has not felt welcoming to me for years. Too corporate, bad algorithms, a stream of discourse I don’t care to contribute to. I just don’t post publicly. But the XOXO Slack has clicked as the place to share myself with more than my IRL friends. It is “the internet” to me in a lot of ways. Like choosing to move to a small town where you end up knowing most folks, it feels comfortable. And this one is filled with artists and cool people. It feels like home, and I’ll be really sad to see it go.


## People 

Responses to the impact also talked about the people that folks had met and how important those people have become. From friendships to a deeper understanding of diverse perspectives and opinions. 

* Just changed my life for the better. I met and connected with amazing people. I’ve never had a safe space like this before. It has inspired every initiative I’ve started since; the warmth of the community has led me to have the same attitude towards other people I encounter in the  world. I’ve never felt so appreciated and welcomed for who I am as a person, and so unafraid to be myself. I appreciate every single person in this community and have made incredible connections with people doing inspiring things. I’m tearing up as I write this. I don’t have enough words to express how I feel, and I don’t think I’m doing it all justice.
* Keeps me connected to so many people. Without this group I really do not have a lot of immediate social connections, especially on specific issues like parenting, portland politics, cooking, etc.
* What a nice group of people.
* It’s really been tremendous. For the people I’ve met, the things I’ve learned, and even the career opportunities that came from being a part of a small network like this. I don’t really do social media otherwise, so it’s really been a salve, especially during the pandemic
* This community has been the closest to feeling like “my people” of anything I have ever experienced.  People here have been consistently welcoming and friendly.  I learn about things I otherwise would have missed on an almost-daily basis.  I feel honored to have this kind of access to so many amazing folks.  XOXO and this community have encouraged me to be less shy about sharing things I do and make.
* Just changed my life for the better. I met and connected with amazing people. I’ve never had a safe space like this before. It has inspired every initiative I’ve started since; the warmth of the community has led me to have the same attitude towards other people I encounter in the  world. I’ve never felt so appreciated and welcomed for who I am as a person, and so unafraid to be myself. I appreciate every single person in this community and have made incredible connections with people doing inspiring things. I’m tearing up as I write this. I don’t have enough words to express how I feel, and I don’t think I’m doing it all justice.
* I've had some professional opportunities thanks to some relationships I've made through XOXO, but those are really just the layer on top of the great personal relationships I've made through the many channels that I participate in.
* The XOXO Slack has been a lifeline for me since 2018. It is a safe and caring place I can go for inspiration and information and assistance and a laugh and new music and job postings. I enjoy supporting others in the community. Being in this community gives me confidence in what I'm doing professionally. I don't feel alone. I know that people care and that there are other people like me. I am so inspired and moved by this community and the people I've met here.
* Made long-term connections I could never keep up otherwise with folks across the planet


### Friendships 

People spoke about the friendships in their lives because of the Slack.

* This community has changed my life. I've made lasting friendships and received career altering advice and assistance from the generosity and intelligence of the people assembled.
* XOXO Slack and XOXO itself has been the highlight of the last decade for me. I've met some amazing friends, had a chance to catch up with my remote coworkers and see some amazing talks.
* This community has been the closest to feeling like “my people” of anything I have ever experienced.  People here have been consistently welcoming and friendly.  I learn about things I otherwise would have missed on an almost-daily basis.  I feel honored to have this kind of access to so many amazing folks.  XOXO and this community have encouraged me to be less shy about sharing things I do and make.
* I've had some professional opportunities thanks to some relationships I've made through XOXO, but those are really just the layer on top of the great personal relationships I've made through the many channels that I participate in.
* I've made many new friends using a communication method that works best for me (online text), as I'm pretty socially anxious. This community has helped me become more authentic and be comfortable with who I am. I have also learned a lot from you all.
* I've met so many cool people in the short time I've been in this Slack, and I was able to connect more deeply with folks I met at my first (and last) XOXO.
* friendships, amazing memories, and an answer to the most esoteric questions imaginable
* I've made some really wonderful lifelong friends here, and it's helped me figure out my healthiest format for a relationship with the Internet (without the risks of the actual Internet)


### Diversity 

* This Slack is by far the most diverse community in which I participate. I grew up in tech, and most tech cohort communities are tediously mono-cultural to the point where I feel alienated from them even if I'm squarely within their demographics. Such communities also tend to have interests limited to those cohorts, and there's more to life than computers.
* First and foremost, I have gained a diversity of thought. I was already an empathetic person, but it helped me understand other people's point of view better. It inspired me to not give up on humanity because there are so many cool, interesting people out there doing cool and interesting things. Many of us are perpetually online and we all have a shared understanding of THE INTERNET that my real-life friends may not have as deep of knowledge of, so I feel a sense of connection that I would crave from social media but actually achieve with XOXO.



### New to the Slack 

Folks who were newer to the Slack also talked about the impact the community had on them.  

* "I'm relatively new to this slack - this last conference was my first. Despite that, it has impacted me a lot. I used to get most of my community on Twitter, but after That Person took it over, I left (cold turkey, as soon as he walked in the door). That was hard, but I knew it was going to slide into a cesspool, and I decided I'd rather leave remembering how good it was than witness its death. 
* XOXO 2024 was my first and only XOXO, so the slack has been and continues to be a huge aspect of my connection to the community and the only non public forum I have to growing it (I am also on xoxo.zone)




## Resources 

Some folks talked about very resources and tangible outcomes from the slack

* Thank you to everyone who has been a part of this special corner of the internet. I’ve learned and grown thanks to this community. And, since I trust the folks here, I’ve found recommendations for everything from medical professionals to professional services over the years - not to mention the support and camaraderie during some hard times.
* The XOXO Slack has been an invaluable resource. From everything with dealing with a global pandemic, to finding a person who can design my bathroom, to discussing video games, and more.
* XOXO Slack and XOXO itself has been the highlight of the last decade for me. I've met some amazing friends, had a chance to catch up with my remote coworkers and see some amazing talks.
* It was my first slack - it's where I hear about beautiful things, and stay connected to important parts of the indie web creator culture



## Personal Growth 

Folks also talked about their own personal growth because of being in the community 

* It brought me to introspect to the point that I now know what I want out of my life and I’m encouraged to pursue it.
* Just changed my life for the better. I met and connected with amazing people. I’ve never had a safe space like this before. It has inspired every initiative I’ve started since; the warmth of the community has led me to have the same attitude towards other people I encounter in the  world. I’ve never felt so appreciated and welcomed for who I am as a person, and so unafraid to be myself. I appreciate every single person in this community and have made incredible connections with people doing inspiring things. I’m tearing up as I write this. I don’t have enough words to express how I feel, and I don’t think I’m doing it all justice.
* XOXO Slack was the setting to my third coming-of-age movie of my life.
* I've gotten way better at online communications.  Seeing how kind, emotionally mature, and patient people have been, and seeing moderators sharing themselves and being human, I think allows me to be more human and kind and patient myself.  I also learned it's okay to vent in a different place, rather than spreading agnst.



## Conversations 

Some folks talked about the  conversations that folks have in the Slack. 

* I joined with the 2019 XOXO and I ended up being so incredibly grateful for this slack community going into the pandemic. It helped give me hope that there were other likeminded folks out there at a time that I went through an existential tech career crisis/burnout. I wish it could just keep on staying the same way it is because I really fear that it will lose a lot of what has made it special in any kind of migration process.
* I literally use the phrase "the social Slack I'm in" ALL THE TIME when I'm talking to friends or my spouse when I talk about things we've done, emoji we use, or threads that have gotten super wild (like the tunnel lady, or the debate stuff)
* XOXO is the only space I’m in right now having important, honest, critical discussions of technology and how it affects our lives/humanity. I’m so grateful to have some role models advocating for better applications of technology and thoughtful decision making about what role technology should play in our lives


### Specific channels 

* As a younger adult without many older adults in my life, I REALLY appreciate the home improvement and gardening channels as a new home owner. I love the regional channels for staying up to date with things at home and places I go. As someone less tech-y I love seeing tech updates from people I agree with politically. I also love the political updates as well! It’s generally a very cathartic space in an incredibly stressful world.
* There are some questions and topics I've been able to ask/discuss in the XOXO Slack that I otherwise would have no idea where I'd turn to. I've really appreciated that and will miss what the slack has become. I hope we're able to rebuild that.
* The XOXO Slack has been an invaluable resource. From everything with dealing with a global pandemic, to finding a person who can design my bathroom, to discussing video games, and more.


### Portland

* I moved to Portland because of it! And this is so common that it won't de-anon me!! And it's given me a much healthier relationship to my work, I don't have to set myself on fire to be a "real" creative person. I can take an afternoon off to take a walk and eat cookies or whatever. I can have a 'capitalism job' for health insurance and money and not apologize for it.
* I got a job through this slack, and it is my best go-to resource on living in Portland.
* I've made friends, found out about local events, hell even the contractor upstairs installing a floor for us is literally a spouse of an XOXO'er who I found through the slack.
* I moved to Portland because of it! And this is so common that it won't de-anon me!! And it's given me a much healthier relationship to my work, I don't have to set myself on fire to be a "real" creative person. I can take an afternoon off to take a walk and eat cookies or whatever. I can have a 'capitalism job' for health insurance and money and not apologize for it.
* Keeps me connected to so many people. Without this group I really do not have a lot of immediate social connections, especially on specific issues like parenting, portland politics, cooking, etc.
* It was a big factor in my decision to move to the Portland area.

### Creativity 

Seeing other creative folks doing things was also important to some. 

* I feel like I have found my people. I am motivated to create and act.
* It’s a huge source of inspiration!
* It has been so nice to see other creative people be open about their doubts and anxieties. This is such a lovely group.




## Care During Hard Times 

One of the themes was that people found that the community cared about them in tough times. The pandemic and challenges with mental health were common. Folks also used the term "lifeline" to refer to the community. 

### Covid 

Many folks talked about how important the Slack Community was for them during the pandemic. 

* XOXO Slack has been a place that I've gone to for comfort and a feeling of community throughout the Covid pandemic and working remotely. Although I haven't engaged much, it's been very comforting to have a place where like-minded people share things they've made and things they care about so openly.
* As I told my husband the news of the Slack winding down, I began to tear up remembering how strongly I felt during the beginning/height of COVID-19 that I would never have made it out with my sanity at the other end without the XOXO Slack. Knowing that there's a community here of people who can be trusted (in many ways) is no small feat. I cherished it.
* Some peace, sanity, and connection especially starting during Covid.
* With the pandemic, this became one of my main sources of community in all the isolation. If it weren’t for Slacks and Discords I would feel even more isolated
* It’s really been tremendous. For the people I’ve met, the things I’ve learned, and even the career opportunities that came from being a part of a small network like this. I don’t really do social media otherwise, so it’s really been a salve, especially during the pandemic
* Having a safe feeling place to keep up on life, the world, tech, ai, COVID, etc, has been so incredibly valuable for me. I think I would be in a very dark place today if I didn’t have the XOXO community to get me through the last few years
* I joined with the 2019 XOXO and I ended up being so incredibly grateful for this slack community going into the pandemic. It helped give me hope that there were other likeminded folks out there at a time that I went through an existential tech career crisis/burnout. I wish it could just keep on staying the same way it is because I really fear that it will lose a lot of what has made it special in any kind of migration process.
* Xoxo slack provided community during the darkest time of the pandemic (and beyond) . I often feel isolated from creative communities which can be cliquish. Xoxo slack is the best type of inclusive community: bringing people together to learn and grow as responsible creative beings on this planet.

### Mental Health 

Some folks spoke about the impact that the community has had on their mental health and well being. 

* I've made many new friends using a communication method that works best for me (online text), as I'm pretty socially anxious. This community has helped me become more authentic and be comfortable with who I am. I have also learned a lot from you all.
* This Slack community has gotten me through times of intense isolation (early pandemic lockdown, cross-country moves, etc). It's a place I've relied on for kind, smart, and fun connection.
* Led me to ADHD and ASD diagnosis. Gifted kind words in trying times. Helped me with purchasing stuff. Made me discover some of my favorite movies. Provides an out for feelings that I have nowhere else to share. Expanded my mind and universe time and again.
* I feel *normal* "here": XOXO slack has helped me appreciate my ADHD (and possible AuDHD!) diagnosis and shown me ways to manage issues without shame. It's a venue for being funny and smart in highly targeted, small audience ways, which is very satisfying. I'm learning to share my visual art with encouragement from that channel. It's the best college dorm/fraternity|sorority (that I never had).
* I think the mental health channels really help me feel validated in a way that I haven’t found in other online communities with similar channels. And I appreciate learning and improving how I interact with other people, even though some of the time it was the hard way.


### Lifeline 

Several people used the word "lifeline" when talking about the Slack or spoke about how important it was for their well being. 

* as a disabled person who doesn't get out a lot, the community has been a lifeline for so many things
* I cannot count the number of times, especially in the last four years, this community has been there for me. I’m pretty sure I’m still alive because of it.
* This Slack was one of my social lifelines during the first year and a half of the pandemic and continued to be a place of solace for me in the years that followed (I had joined in summer of 2019). I don’t know what life would have been like without it, but it would have been harder.
* The XOXO Slack is my first stop every morning, and often one of my last stops at night. I may not always post, but it feels like the best water cooler/group chat/pin board of cool things and feelings. XOXO Slack members and the festival have helped me finally get therapy, get a better sense of boundaries, open my eyes and mind to amazingly wonderful individuals, realize that I am not alone in being hopelessly excited about good things in the world, and really did a lot of heavy lifting emotionally and socially in 2016 and 2020. Thank you friends.
* XOXO Slack has been a place that I've gone to for comfort and a feeling of community throughout the Covid pandemic and working remotely. Although I haven't engaged much, it's been very comforting to have a place where like-minded people share things they've made and things they care about so openly.
* XOXO Slack has helped me feel less alone online and IRL, helped me process and recognize feelings and experience I didn't know were shared and common. XOXO Slack has helped me meet some wonderful people and understand how not alone I am in the world. In practical terms, people * * I've meet through XOXO are all around me - zines, postcards, letters, stickers I've gotten over the years. XOXOers have generously gifted me furniture when I moved, pointed me to internet providers and electricity, stayed in my apartment and left me wonderful snacks and gifts and overall - always always always been helpful and amazing and omnipresent in my life for the last 8 years since I first went to the festival.
* The community has improved my well being, quality of life, pointed me to resources for diversity, inclusion, equity, activism, and opened my eyes to better ways of living.
* Having a safe feeling place to keep up on life, the world, tech, ai, COVID, etc, has been so incredibly valuable for me. I think I would be in a very dark place today if I didn’t have the XOXO community to get me through the last few years
* Has, without exaggeration, saved my life three times.
* it was such a lifeline during lock down, and a sanity check during rough political waves



## Safe Space 

We heard again that this was a safe space. 

* It’s been a safe space.
* This community has been my stable source of support for the past ten years—personally and professionally. It’s been a close-knit community of like-minded folx and an online space where I don’t feel like I am competing for popularity or influencer status, where I can fluctuate my engagement with little FOMO, and where curiosity or humility is embraced and not shamed or ridiculed. It’s been a space that fosters a spectrum of interests and topics, whether a deep dive on a tangential topic, showcasing an inspiring creative project, or just a small-talk conversation.
* Having a safe feeling place to keep up on life, the world, tech, ai, COVID, etc, has been so incredibly valuable for me. I think I would be in a very dark place today if I didn’t have the XOXO community to get me through the last few years
* Just changed my life for the better. I met and connected with amazing people. I’ve never had a safe space like this before. It has inspired every initiative I’ve started since; the warmth of the community has led me to have the same attitude towards other people I encounter in the  world. I’ve never felt so appreciated and welcomed for who I am as a person, and so unafraid to be myself. I appreciate every single person in this community and have made incredible connections with people doing inspiring things. I’m tearing up as I write this. I don’t have enough words to express how I feel, and I don’t think I’m doing it all justice.
* The internet is terrifying and I never thought I'd find a place where I felt safe enough to talk with strangers.
* Thank you to everyone who has been a part of this special corner of the internet. I’ve learned and grown thanks to this community. And, since I trust the folks here, I’ve found recommendations for everything from medical professionals to professional services over the years - not to mention the support and camaraderie during some hard times.
* I genuinely believe this Slack saved me through the pandemic from dealing with isolation and lost connection. I was on a medical leave from my job shortly before things shut down and relied on the Slack for daily interaction besides my spouse as a lot of other relationships fluctuated. Even just observing or reacting with emoji built connection for me that led to being more conversational, more mindful, and more confident to speak in channels.


## General Gratitude 

Finally, some folks just wanted to say thank you. 

* Words are hard to find. SO grateful for all of it. What a special thing to have been a part of!
* More ways than I can describe!!
* I love this place, not sure how else to put it.
* Because of that I actually feel more prepared for this evolution/change/dissolution. It has been wonderful to be a part of it, and I'm not afraid. I know I'll find my people again.
