
# Thank You to The Andys

In the survey we offered up a chance for folks to express their gratitude. And this community took their gratitude seriously. 

Buckle up folks and bring out those kleenex. Here's our community note of gratitude to you both. 


Dear Andys, 

You're the best, we think the world of you. You made a community, one that was kind and that helped us remember the good internet. We saw how hard you worked. You changed lives and you should be proud of what you've done. We are so grateful and we the community will take it from here. Thank you. 

Love, the XOXO community


## You're the Best 

* the best Andy's ever.
* y'all are literally THE BEST. please be proud of what you've done! I know as a creator you always compare what exists in the world with the perfect thing you imagined in your head but what you made was and is AMAZING. You did great!!
* XOXO is (was?) my favorite thing. Not my favorite conference, not my favorite Slack instance. My favorite thing, period.
* There are no words. What the Andys created was pure magic and will never be duplicated. Thank you for the love, laughs and tears. You are the best!
* You're the best. Thank you for everything.


## We Think the World of You

* Andys, for everything wonderful about what you've made, I hope you also know that it's okay to walk away. We'll miss it, but you've already done the work and we can take it from here. It's okay for beautiful things to end, and to create space for new things to grow."
* Thank you so much Andy and Andy. The XOXO Slack Community is very special.
* Thank you to the Andys and Rachel for all their consideration and mindfulness. I feel like this community has welcomed me, educated me,  and included me in ways no other social community has before. It’s so beautiful and I hope you never forget all you’ve given and what you’ve grown with us. Big thank you.
* Andys, whether you knew it or not, you've been amazing mentors for me.  So often, social (and business) spaces have been so inhuman and inhumane, and you made XOXO Slack welcoming, human, and just plain nice.  Seeing it actually done for real is a huge accomplishment and an inspiration to me and others.  I am so grateful.  Thank you.
* No small part of the magic of the XOXO community has been due to your thoughtful and careful curation.  Thank you!
* You two absolute mensches have poured your love into our community, have helped *make* us a community and not just a herd of somewhat feral cats. You've made thoughtful choices, over and over, curating as caretaking, looking after your creation even at real cost. You are personally responsible for more #good-internet than you can ever know. Your legacy will last as long as humans know the internet existed. Thank you for gathering up all the folks from my home planet; it was lonely before we had each other.
* You guys already know I love you because I text you all the time so... yea
* "They must already know the massive impact they've had on this community, and the internet at large. xoxo is a legendary event, and its impact will be long-reaching. They brought people together, and helped those people share ideas. What a wonderful thing to spend the rest of your life knowing that you did. 
* Andy Andy Andy Andy


## You Made a Community

* you made an amazing community, thank you.
* This community is hands down the best thing about XOXO. I'm glad that the festival and conference was the catalyst for it.
* It’s rare to create such a wonderful community. I’m deeply appreciative of all the work you and all the volunteers have put into making XOXO
* OMG Thank you for creating something so incredible, and so meaningful to people! Happy retirement!
* XOXO has filled a spot in my heart that I didn't even know I needed. I feel so lucky to be apart of this in such a minor way. Thank you for bringing such a unique group of people together and giving them a space to share their really cool brains.
* "Communities are as much expressions of their leaders and maintainers as they are products of their members. The Andys have used their talents and experience to give us a place to be that is unlike any other online, and I am most grateful
* There is grace is knowing that all things end, and recognizing the responsibility to end things well. Thank you for throwing one last party, and for ushering the XOXO Slack community towards its next evolution."
* Thank you for being brave enough, and hard working enough to build such an incredible community and experience.
* Most important community in my life, my gratitude is immeasurable
* This is such a special, strong, and amazing community. I really do not know how I would have gotten through having-a-baby-during-COVID without it.
* I have tons of respect for how you've built up this community! I'm sad to see it end, but I think it was 100% the correct decision. I look forward to learning about what you do next.
* Thank you for all that you have done with a big nod for allowing one last gathering so members could get a sense of closure. Also, thnx for allowing the community three months to wind down and still leave what was hear archived so people can find things in the future, Very well done gentlemen.
* Thanks. Believe it or not, this community has replaced MetaFilter for me, which was my previous ride-or-die. Knowing what I do about communities like this, I honestly can’t believe you’ve been able to foster such a great place for this long. It’s very smart to make this transition when things are on an upswing.


## A Community that was Kind 

* This has been the best-run, most useful and least-asshole-ish virtual community at scale that I’ve been a part of, honestly. Even just as a Portland resource for vendors, etc, it’s amazing. Thank you for manifesting your kindness and thoughtfulness into this living artifact.
* Thank you for creating one of the most considerate, welcoming, and respectful communities I've ever had a chance to be a part of. The festival is always great fun, but the community has been an invaluable part of my life for the past 8 years. Given how bleak those of those years have been, I'm really not sure how I'd have got through them without the constant support, company, and mutual commiseration of the XOXO community.
* I am incredibly impressed by the level of kindness and goodwill that is displayed not just in the community but in your approach to building and maintaining it. I aspire to fostering similar community where I am called to do so. Thank you for putting so much of yourselves into this for so long even when I am sure it was very hard.
* This community has been a real comfort to me as I navigate life. I don’t know of another place where there are so many smart, lovely and supportive folks in one place.
* Truly unique and powerful experiences, ripples of creativity and human connection that will continue for years and years to come. With all the kids at the last one…for generations even!



## You Helped us Remember the Good Internet 

* Andys, you did something I never thought I'd ever see in the world. You created space for an increasingly diverse and varied gathering of people to get deeply into their feelings, from anger and sorrow through excitement and joy, all in the name of celebrating weird and neat things made possible by the internet and technology. What an absolutely incredible treasure this has been. Thank you.
* XOXO is a remarkable, unique, and pretty much unchallenged take at creating a real-world representation of the hope and power of the connected world through technology, without forgetting that there are people around every corner, decision, design, platform, and "product". I will miss it but also take the experience in person and online with me with every one of my endeavors and experiences. It is an unforgettable force and experience and will difficult to move forward without remembering it, being influenced by it, or flat-out trying to steal (ok, maybe "share" is better) it's pure energy and power .
* Thank you for keeping the spirit of the Good Internet alive, we hope to continue it
* In a particular part of my life, I can only point to one other thing that has meant so much to me and that is the Internet, or maybe more specifically the web, itself. XOXO is the best of the Internet in human form. It embodies the wholesome goodness that is the Internet. When I think about it, I literally get choked up and think to myself, 'how is it possible this existed and how lucky am I to have been a small part of it a few times.' I really wish I could find the words to express what it means to me. And I am just ONE of the lucky people that got to experience it. How lovely. How profound.


## We Saw How Hard You Worked 

* Your dedication to keeping this weird thing alive is truly inspiring. I cannot imagine the amount of effort and time it’s taken to moderate this, and create such a positive structure. I guess all I can really say is: well fucking done.
* Your emotional labor was not in vain and did not go unseen.
* It’s a lot of work to curate people and ideas, especially in a way that is inclusive, yet expansive. Thank you, Andy’s, for creating the space for us to connect, learn, experience joy, share angst, collaborate on ideas and tools to express the best part of ourselves.
* Thank you for all of the hard work and thought you put into the slack community over the years to make it such a welcoming and empathetic space that I now feel devastated to lose!
* Community moderation is hard but you make it look easy


## You Changed Lives 

* Thank you from the bottom of my heart. XOXO changed my life and I appreciate the phenomenal effort you have put into creating a space where people feel safe to be their true selves. You have done something truly amazing and connected hundreds of people in a way that I don’t think any other community I encounter will ever compare.
* In terms of life's work, this is pretty excellent.
* Thank you for creating a wonderful community! The XOXO conference has been life-changing. I'm so sad that it's the last IRL time, but I'm glad I got to attend multiple times.
* Y’all have changed my life, multiple times, since my first XOXO in 2015. I literally wouldn’t be here without you and what you’ve helped create. I will never be able to repay that, but I try every day. Thank you seems insufficient, but it’s a start: thank you.
* I firmly believe that the XOXO community saved lives during the Trump administration and the pandemic, and I am thankful for that. I came for the talks and found a community.
* They created a lifeline and one of the few places where I feel hopeful, understood, and welcome. They also have modeled how to be a better person.
* Thank you. I'm not the same person I was in 2012 when I attended my first XOXO and as the community grew and changed, so did I. Thank you for starting something special and caring enough to continue it despite challenges. When I reflect on XOXO, it's one of the most life changing things I could've encountered and feel lucky and fortunate for the friendships I've made and the lessons I've learned over the past 12 (wow!) years


## You Should be Proud 

* I think y'all should be really proud of what you built! It was an amazing experience for so many people and I'm grateful I got to be part of it.
* You should be so proud
* You should be very proud. And yet, in the many years I’ve known you, you remain humble and practically defiant of any ego. You not only built a festival and an event that remains my standard of excellence, but you also fostered a decade-long community with shared values and creative curiosity across a variety of mediums and niche interests. Your leadership is aspirational: you come to the table with big ideas but also practical next steps, you proactively plan for inclusivity instead of the bare minimum of reactionary accessibility, and you empower self-organization in the community and amongst support staff while balancing appropriate management with genuine encouragement. The XOXO community has been indescribably my closest network—inspirational, supportive, and empathetic. While the final festival and archiving of the Slack workspace is bittersweet, it’s also a cathartic transition I needed post-2020.



## We are So Grateful 

* i'm so grateful for the work y'all put in on this whole thing~
* Thank you for the opportunity to be in Portland in 2018 gratis. It was a meaningful experience that continues to impact my life positively.
* So much gratitude and appreciation. thank you again.
* I am grateful- so grateful
* I feel very lucky to have been able to be a part of such a wonderful community and I am deeply, deeply grateful that it existed to begin with.
* Thank you. With every ounce of love that I can muster from every corner of my heart, thank you.
* You have enough folks telling you, you’ve created something special and that it’ll be missed. I hope you get to see the 1000s of flowers bloom that you seeded here, thank you for everything <3


## We Got It From Here 

* Gentlemen, thank you, and please take a break, toast each other with a beverage, and know you’ve built a great place. To quote an album title, We got it from here, thank you for your service.
* Enjoy your rest, we’ve got it from here!
* You created this community and you will always be a part of it, but you don't have to worry. We've got it. Time for us to leave the nest.
* Thank you. You couldn't have known what we would become and thank you for supporting this cultural experiment. We're ready for what's next.




## All The Thank You's 

Thank you, thank you, thank you! I hope I get to see what you each do next.
Thank you!
Thank you
Thank you so much for all you’ve done in creating this wonderfully kind little slice of the internet.
Thank you for years of XOXO and curating this community
THANK YOUUUUUUUUUU
Thank you, for everything!
thank you for 10+ years of what came to be my favorite online community.
Thank you.
thank you, you have changed my life for the better!
Thank you.
Thank you.
Thank you. Really— thank you.
Thank you. A big heartfelt thank you.
Thanks a lot, guys, it’s been such a fun ride
A million, million thank yous!
Thanks guys. You made the thing, and it mattered to people.
Thank you! You made something good in the world.
Thank you!!
Thank you!
Thank You so very very very much
Thank you for this gift to the world.
Wow!
Thank you, you’ve done a good thing here.
Thank you for making such a beautiful community of brilliant minds.
Thank you!!
Words can't do it justice, but a very sincere thank you.
Thank you so much--I cannot express how much you have changed my life!
There's a lot I could say, but all of it is: "thank you"
Thank you, thank you, thank you!
Thank you for giving so much of yourselves.
Thank you Andys! This is a really really special community. I feel so fortunate to get to be a part of it.
Thank you. You raised my expectations
Thank you!!!
Thank you for creating a corner of the internet and real life that didn't succumb to enshittification.
Thank you for everything. Thank you very, very, very much.
Thank you.
good job!
Just immense thanks and gratitude.
thank you for this incredible community
Thank you for bringing such wonderful people together.
<3

